# Generated by Django 4.0.2 on 2022-02-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='nombres',
        ),
        migrations.AddField(
            model_name='autor',
            name='nombre',
            field=models.CharField(default='Rodrigo', max_length=255, verbose_name='Nombre de autor'),
            preserve_default=False,
        ),
    ]
